### ISSUE TITLE
Uncapp

### ISSUE THREAD

**Issue by guillempalau** [HelenFoster/AnkiAddons#5]
Hi Helen,

I am using your add-on. I have counts above 1000 which I'd like to show. I thought that commenting lines 78 and 79 would do the trick as I did back in 2.0.x from another add-on but same monkey patching method. 

At least in Anki 2.1.20 does not get rid of the cap. Could you point out what needs to be modified? 

Thank you

**Comment by HelenFoster** [comment]
Hi, it looks like there's a bit of duplication in the Anki code. In 2.1.20 we have:
* deckbrowser.py line 227 `cnt = "1000+"` (which my code replaces)
* sched.py line 31 `self.reportLimit = 1000` and various functions which refer to it

So you're right about what to comment out. And I think you also need to fit e.g. `mw.col.sched.reportLimit = 10000` in somewhere. But it can't go in the addon initialization because that object doesn't exist yet. And it can't go in _renderDeckTree because that's too late.
